name: telegram_userbot_gratis_android
description: A Library Full Package Template
version: 0.0.0
homepage: https://github.com/azkadev/telegram_userbot_gratis
repository: https://github.com/azkadev/telegram_userbot_gratis
issue_tracker: https://github.com/azkadev/telegram_userbot_gratis/issues 
documentation: https://youtube.com/@azkadev
funding:
  - https://github.com/sponsors/azkadev


platforms:
 android:
 ios:
 linux:
 macos:
 web:
 windows:

# topics:
#   - telegram_userbot_gratis
#   - telegram_userbot_gratis_flutter
#   - telegram_userbot_gratis_dart

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
 
flutter:
 